apiVersion: v1
kind: Secret
metadata:
  name: fintech-secrets
  namespace: fintech
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=
  postgres-password: cm9vdHBhc3M=
  mongodb-root-username: cm9vdHVzZXI=
  mongodb-root-password: cm9vdHBhc3M=
  jwt-secret: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
  gmail-username: Z29zcGVsdWRlY2h1a3d1MjdAZ21haWwuY29t
  gmail-password: bm9hZXhyYWJ1dnhoZGJxYg==
  pgadmin-email: Z29zcGVsdWRlY2h1a3d1MjdAZ21haWwuY29t
  pgadmin-password: YWRtaW4=
