apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: fintech-microservices-discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVER_URI
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "discovery-server"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: fintech
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
