apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: fintech-microservices-user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8091
          env:
            - name: CONFIG_SERVER_URI
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "user-service"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb"
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: mongodb-root-username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: mongodb-root-password
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: "admin"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: jwt-secret
          readinessProbe:
            tcpSocket:
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8091
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: fintech
spec:
  selector:
    app: user-service
  ports:
    - port: 8091
      targetPort: 8091
  type: ClusterIP
